# Generated by Django 6.0.3 on 2026-03-28 10:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField(editable=False)),
                ('adults', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('children', models.PositiveIntegerField(default=0)),
                ('include_breakfast', models.BooleanField(default=False)),
                ('include_lessons', models.BooleanField(default=False)),
                ('lessons_count', models.PositiveIntegerField(default=0)),
                ('include_board_rental', models.BooleanField(default=False)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breakfast_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lessons_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('board_rental_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('paid', 'Оплачено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращено')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='camps.surfcamp')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('surf_level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20)),
                ('emergency_name', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='bookings.booking')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('method', models.CharField(choices=[('card', 'Банковская карта'), ('paypal', 'PayPal'), ('bank_transfer', 'Банковский перевод')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='bookings_bo_booking_03d631_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='bookings_bo_check_i_3b9851_idx'),
        ),
    ]
