# Generated by Django 6.0.3 on 2026-04-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package_type',
            field=models.CharField(choices=[('full', 'С уроками'), ('bnb', 'Только проживание (B&B)')], default='full', max_length=10),
        ),
    ]
