# Generated by Django 6.0.3 on 2026-03-30 05:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='providers/logos/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='providers/images/')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_providers', to='camps.region')),
            ],
            options={
                'ordering': ['-is_featured', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='SurfLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('short_description_ru', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(blank=True)),
                ('lesson_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('semi_private', 'Semi-Private')], default='group', max_length=20)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='beginner', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('max_participants', models.PositiveIntegerField(default=6)),
                ('min_age', models.PositiveIntegerField(default=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_per_person', models.BooleanField(default=True)),
                ('is_package', models.BooleanField(default=False)),
                ('lessons_in_package', models.PositiveIntegerField(default=1)),
                ('package_discount_percent', models.PositiveIntegerField(default=0)),
                ('includes_equipment', models.BooleanField(default=True)),
                ('includes_wetsuit', models.BooleanField(default=True)),
                ('includes_transport', models.BooleanField(default=False)),
                ('includes_photos', models.BooleanField(default=False)),
                ('includes_video', models.BooleanField(default=False)),
                ('includes_theory', models.BooleanField(default=True)),
                ('includes_insurance', models.BooleanField(default=False)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='lessons/')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('bookings_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.lessonprovider')),
            ],
            options={
                'ordering': ['-is_featured', '-rating', 'price'],
            },
        ),
        migrations.CreateModel(
            name='LessonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_country', models.CharField(blank=True, max_length=100)),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('surf_level', models.CharField(blank=True, max_length=20)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lessons.surflesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lessons/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lessons.surflesson')),
            ],
            options={
                'ordering': ['-is_main', 'order'],
            },
        ),
    ]
