# Generated by Django 6.0.3 on 2026-03-28 06:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (CSS класс)')),
                ('category', models.CharField(choices=[('accommodation', 'Проживание'), ('food', 'Питание'), ('surf', 'Серфинг'), ('activities', 'Активности'), ('services', 'Сервисы')], default='services', max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('name_en', models.CharField(max_length=50, verbose_name='Название (EN)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (CSS класс)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип доски',
                'verbose_name_plural': 'Типы досок',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код страны')),
                ('image', models.ImageField(blank=True, null=True, upload_to='countries/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='camps.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SurfCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('history', models.TextField(blank=True, verbose_name='История школы')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Долгота')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь (USD)')),
                ('price_per_lesson', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за урок (USD)')),
                ('has_bed_breakfast', models.BooleanField(default=False, verbose_name='Bed & Breakfast (без уроков)')),
                ('bed_breakfast_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена B&B за ночь (USD)')),
                ('skill_levels', models.JSONField(default=list, verbose_name='Уровни серфинга')),
                ('board_rental_available', models.BooleanField(default=True, verbose_name='Аренда досок')),
                ('board_rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена аренды доски/день (USD)')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Бассейн')),
                ('has_restaurant', models.BooleanField(default=False, verbose_name='Ресторан')),
                ('has_yoga', models.BooleanField(default=False, verbose_name='Йога')),
                ('has_parties', models.BooleanField(default=False, verbose_name='Вечеринки')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='camps', to='camps.amenity', verbose_name='Удобства')),
                ('board_types', models.ManyToManyField(blank=True, related_name='camps', to='camps.boardtype', verbose_name='Типы досок')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camps', to='camps.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Серф-кемп',
                'verbose_name_plural': 'Серф-кемпы',
                'ordering': ['-is_featured', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_country', models.CharField(blank=True, max_length=100, verbose_name='Страна автора')),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото автора')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('surf_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, verbose_name='Уровень серфинга')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Дата визита')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='camps.surfcamp', verbose_name='Кемп')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('certifications', models.CharField(blank=True, max_length=300, verbose_name='Сертификаты')),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='Языки')),
                ('is_head_coach', models.BooleanField(default=False, verbose_name='Главный тренер')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='camps.surfcamp', verbose_name='Кемп')),
            ],
            options={
                'verbose_name': 'Инструктор',
                'verbose_name_plural': 'Инструкторы',
                'ordering': ['-is_head_coach', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camps/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='camps.surfcamp', verbose_name='Кемп')),
            ],
            options={
                'verbose_name': 'Изображение кемпа',
                'verbose_name_plural': 'Изображения кемпов',
                'ordering': ['order', '-is_main'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (USD)')),
                ('is_included', models.BooleanField(default=False, verbose_name='Включено в стоимость')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='Изображение')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='camps.surfcamp', verbose_name='Кемп')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
            },
        ),
    ]
