# Generated by Django 6.0.3 on 2026-04-07 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfcamp',
            name='discount_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание скидки'),
        ),
        migrations.AddField(
            model_name='surfcamp',
            name='discount_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Скидка действует до'),
        ),
        migrations.AddField(
            model_name='surfcamp',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='Скидка (%)'),
        ),
    ]
