# Generated by Django 6.0.3 on 2026-04-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0003_add_teaching_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfcamp',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='surfcamp',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
