# Generated by Django 6.0.3 on 2026-04-14 08:42

from django.db import migrations, models
from django.utils.text import slugify


def populate_country_slugs(apps, schema_editor):
    Country = apps.get_model('camps', 'Country')
    for country in Country.objects.all():
        base = slugify(country.name_en) or country.code.lower()
        slug = base
        i = 2
        while Country.objects.filter(slug=slug).exclude(pk=country.pk).exists():
            slug = f"{base}-{i}"
            i += 1
        country.slug = slug
        country.save(update_fields=['slug'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0004_alter_surfcamp_latitude_alter_surfcamp_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='landing_faq',
            field=models.JSONField(blank=True, default=list, verbose_name='FAQ [{q, a}]'),
        ),
        migrations.AddField(
            model_name='country',
            name='landing_h1',
            field=models.CharField(blank=True, max_length=200, verbose_name='H1 для лендинга'),
        ),
        migrations.AddField(
            model_name='country',
            name='landing_intro',
            field=models.TextField(blank=True, verbose_name='Intro-текст лендинга'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO title'),
        ),
        # Add slug as nullable first, populate, then enforce unique.
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=100, verbose_name='URL slug'),
        ),
        migrations.RunPython(populate_country_slugs, reverse_noop),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL slug'),
        ),
    ]
