# Generated by Django 6.0.3 on 2026-04-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0005_country_landing_faq_country_landing_h1_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='surfcamp',
            constraint=models.UniqueConstraint(fields=('name', 'region'), name='unique_camp_name_per_region'),
        ),
    ]
