# Generated by Django 6.0.3 on 2026-03-28 06:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Долгота')),
                ('wave_direction', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'A-Frame (Both)')], max_length=10, verbose_name='Направление волны')),
                ('wave_type', models.CharField(choices=[('beach', 'Beach Break'), ('reef', 'Reef Break'), ('point', 'Point Break')], max_length=10, verbose_name='Тип волны')),
                ('wave_height_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Мин. высота волны (м)')),
                ('wave_height_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Макс. высота волны (м)')),
                ('skill_levels', models.JSONField(default=list, verbose_name='Подходящие уровни')),
                ('best_tide', models.CharField(blank=True, max_length=50, verbose_name='Лучший прилив')),
                ('best_swell', models.CharField(blank=True, max_length=100, verbose_name='Лучший свелл')),
                ('best_wind', models.CharField(blank=True, max_length=100, verbose_name='Лучший ветер')),
                ('best_season', models.CharField(blank=True, max_length=100, verbose_name='Лучший сезон')),
                ('crowd_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20, verbose_name='Загруженность')),
                ('hazards', models.TextField(blank=True, verbose_name='Опасности')),
                ('has_rocks', models.BooleanField(default=False, verbose_name='Камни')),
                ('has_reef', models.BooleanField(default=False, verbose_name='Риф')),
                ('has_currents', models.BooleanField(default=False, verbose_name='Течения')),
                ('has_sharks', models.BooleanField(default=False, verbose_name='Акулы')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Парковка')),
                ('has_showers', models.BooleanField(default=False, verbose_name='Душ')),
                ('has_rentals', models.BooleanField(default=False, verbose_name='Прокат')),
                ('has_cafe', models.BooleanField(default=False, verbose_name='Кафе')),
                ('has_lifeguard', models.BooleanField(default=False, verbose_name='Спасатели')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camps', models.ManyToManyField(blank=True, related_name='spots', to='camps.surfcamp', verbose_name='Кемпы рядом')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='camps.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Серф-спот',
                'verbose_name_plural': 'Серф-споты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spots/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spots.surfspot', verbose_name='Спот')),
            ],
            options={
                'verbose_name': 'Изображение спота',
                'verbose_name_plural': 'Изображения спотов',
                'ordering': ['order', '-is_main'],
            },
        ),
    ]
